builtin_interfaces/Time stamp
float64 source_timestamp
bool source_timestamp_valid
bool valid

float64[] filter_input
float64[] filter_output
float64[] filter_state_before
float64[] filter_state_derivative
float64[] filter_state_after

float64 dither_phase_rad
bool dither_phase_valid
float64 dither_amplitude_m
bool dither_amplitude_valid
float64 dither_angular_frequency_rad_sec
bool dither_angular_frequency_valid
