"""Independent equations for R15 math; empirical gates live in the study."""
import json
import math

import numpy as np
import pytest

from ros_esc.filter_node.harmonic_gesc import fit_reduced_profile

BETA = np.array([.03, -.02, .009, .006, -.004, .003])


def samples(*, quadratic=False, noise=False):
    t = np.arange(180)/20.
    phase = .31+math.tau*t/3.
    x = .025*(np.cos(.35*t)-1.)
    y = .025*np.sin(.35*t)
    raw = -1.+.004*t+.2*x-.1*y
    for k in (1, 2, 3):
        raw += BETA[2*k-2]*np.cos(k*phase)+BETA[2*k-1]*np.sin(k*phase)
    if quadratic:
        raw += .5*x*x-.4*x*y+.3*y*y
    if noise:
        # Independent deterministic broadband residual, not generated by fit.
        raw += .004*np.sin(7.37*t)+.002*np.cos(11.91*t)
    return np.column_stack((t, x, y, phase, raw, np.arange(180)//60))


@pytest.mark.parametrize('degree', [1, 2])
def test_exact_curved_motion_signal_recovered(degree):
    fit = fit_reduced_profile(samples(quadratic=degree == 2), spatial_degree=degree)
    assert fit['valid'], fit
    np.testing.assert_allclose(fit['coefficients'], BETA, atol=2e-9, rtol=1e-8)
    np.testing.assert_allclose(fit['cv_gains'], [1., 1., 1.], atol=2e-7)
    assert fit['latest_prediction_pass']


@pytest.mark.parametrize('degree', [1, 2])
def test_origin_changes_preserve_coefficients_and_correlated_noise_scale(degree):
    data = samples(quadratic=degree == 2, noise=True)
    fit = fit_reduced_profile(data, spatial_degree=degree)
    shifted = data.copy()
    shifted[:, 0] += 10000.
    shifted[:, 1] += 3.
    shifted[:, 2] -= 5.
    moved = fit_reduced_profile(shifted, spatial_degree=degree)
    assert fit['valid'] and moved['valid'], (fit, moved)
    np.testing.assert_allclose(moved['coefficients'], fit['coefficients'], atol=1e-9)
    np.testing.assert_allclose(moved['covariance_hac'], fit['covariance_hac'], atol=1e-12)
    assert moved['signal_score'] == pytest.approx(fit['signal_score'], rel=1e-7)
    assert np.linalg.eigvalsh(fit['covariance_hac']).min() >= -1e-18


@pytest.mark.parametrize('degree', [1, 2])
def test_world_rotation_rotates_harmonic_covariance_and_preserves_score(degree):
    data = samples(noise=True)
    fit = fit_reduced_profile(data, spatial_degree=degree)
    angle = .72
    rotated = data.copy()
    r = np.array([[math.cos(angle), -math.sin(angle)],
                  [math.sin(angle), math.cos(angle)]])
    rotated[:, 1:3] = data[:, 1:3]@r.T
    rotated[:, 3] += angle
    changed = fit_reduced_profile(rotated, spatial_degree=degree)
    transform = np.zeros((6, 6))
    for k in (1, 2, 3):
        c, s = math.cos(k*angle), math.sin(k*angle)
        transform[2*k-2:2*k, 2*k-2:2*k] = [[c, -s], [s, c]]
    assert fit['valid'] and changed['valid'], (fit, changed)
    np.testing.assert_allclose(changed['coefficients'], transform@fit['coefficients'], atol=1e-9)
    np.testing.assert_allclose(changed['covariance_hac'],
                               transform@fit['covariance_hac']@transform.T, atol=1e-12)
    assert changed['signal_score'] == pytest.approx(fit['signal_score'], rel=1e-7)


@pytest.mark.parametrize('degree', [1, 2])
def test_cost_units_scale_estimate_and_uncertainty_together(degree):
    data = samples(noise=True)
    fit = fit_reduced_profile(data, spatial_degree=degree)
    data[:, 4] = -7.*data[:, 4]+13.
    changed = fit_reduced_profile(data, spatial_degree=degree)
    assert fit['valid'] and changed['valid']
    np.testing.assert_allclose(changed['coefficients'], -7.*np.array(fit['coefficients']), atol=1e-9)
    np.testing.assert_allclose(changed['covariance_hac'], 49.*np.array(fit['covariance_hac']), atol=1e-11)
    assert changed['signal_score'] == pytest.approx(fit['signal_score'], rel=1e-7)


def test_quadratic_nuisance_rejects_exact_phase_curvature_ambiguity():
    data = samples()
    phase = data[:, 3]
    data[:, 1] = .025*np.cos(phase/2.)
    data[:, 2] = .025*np.sin(phase/2.)
    data[:, 4] = -1.+20.*(data[:, 1]**2-data[:, 2]**2)
    fit = fit_reduced_profile(data, spatial_degree=2)
    assert not fit['valid'], fit
    assert fit['reason'] == 'phase_motion_confounded'


@pytest.mark.parametrize('change', ['loss', 'reversal'])
def test_latest_prediction_rejects_complete_cycle_change(change):
    data = samples()
    data[:, 1:3] = 0.
    signal = .03*np.cos(data[:, 3])
    data[:, 4] = -1.+signal
    latest = data[:, 5] == 2
    data[latest, 4] = -1. if change == 'loss' else -1.-signal[latest]
    fit = fit_reduced_profile(data)
    assert fit['valid'], fit
    assert not fit['latest_prediction_pass'], fit
    assert fit['cv_gains'][-1] < 0.


@pytest.mark.parametrize('degree', [0, 3, True, None])
def test_invalid_model_degree_unavailable(degree):
    fit = fit_reduced_profile(samples(), spatial_degree=degree)
    assert not fit['valid']
    assert fit['reason'] == 'invalid_spatial_degree'


def test_nonfinite_or_unsupported_samples_remain_unavailable():
    data = samples()
    data[20, 4] = np.nan
    fit = fit_reduced_profile(data)
    assert not fit['valid']
    json.dumps(fit, allow_nan=False)
    data = samples()
    data[90:, 0] += .6
    fit = fit_reduced_profile(data)
    assert not fit['valid']
    assert fit['reason'] == 'source_gap_or_order'
